### ISSUE TITLE
Doc comments

### ISSUE THREAD

**Issue by jomala** [magiclen/enum-ordinalize#3]
It would be good if a `///` doc comment before the macro was applied to the enum. I believe https://stackoverflow.com/a/33999625 explains how this can be done, but I've little experience with macros and haven't attempted to validate this.

**Comment by magiclen** [comment]
The doc comments can be written in a common way like the follow code,

```rust
#[macro_use] extern crate enum_ordinalize;

/// Here is the doc comment.
#[derive(Debug, PartialEq, Eq, Ordinalize)]
enum MyEnum {
    Zero,
    One,
    Two,
}
```

**Comment by jmlMetaswitch** [comment]
Definitely works with version 3.0.1. Thank you!
