### ISSUE TITLE
Provide Changelog

### ISSUE THREAD

**Issue by The-Fireplace** [magiclen/enum-ordinalize#8]
As a developer, I would like to know what is changing when upgrading to a new version of enum-ordinalize. Is there a changelog somewhere with the changes made with version 4.0.0, or can you make one?

**Comment by magiclen** [comment]
Sorry for the inconvenience.

In version 3, functions are implements directly on the enum. In version 4, the `Ordinalize` trait will be implemented for those enums that have the `#[derive(Ordinalize)]` attritube.
